#coding:utf-8

# APPLICATIONS.FINANCE.CURRENCY MODEL
CURRENCY_DEBIT = True
CURRENCY_CREDIT = False
# APPLICATIONS.FINANCE.CURRENCY VIEW
CURRENCY_COLSPAN = 9 # Ерөнхий журнал/Туслах журналын хүнэгтийн баганын тоо


# APPLICATIONS.FINANCE.ACCOUNT MODEL - Дансны төрөл
ACCOUNT_ACTIVE = 'ACT'
ACCOUNT_PASSIVE = 'PAS'
ACCOUNT_INCOME = 'INC'
ACCOUNT_EXPENSE = 'EXP'
# APPLICATIONS.FINANCE.ACCOUNT MODEL - Дансны шинж
ACCOUNT_GROUP = 'GRP' # Дансны бүлэг
ACCOUNT_PARENT = 'PAR' # Эцэг данс
ACCOUNT_ACCOUNT = 'ACC' # Навч данс


# APPLICATIONS.BASIC.CUSTOMER MODEL - Харилцагчийн төрөл
CUSTOMER_STUFF = 'STU' # Дотоод ажилтан
CUSTOMER_PERSON = 'PER' # Хувь хүн
CUSTOMER_ORG = 'ORG' # Аж ахуй нэгж
CUSTOMER_OTHER = 'OTH' # Бусад


# APPLICATIONS.CONFIG MODEL - Авах утгын төрөл
CONFIG_TYPE_INTEGER = 'INT' # Тоон утга
CONFIG_TYPE_FLOAT = 'FLT' # Бутархай тоон утга
CONFIG_TYPE_PERCENT = 'PER' # Хувь
CONFIG_TYPE_TEXT = 'TXT' # Текстэн мэдээлэл
CONFIG_TYPE_ACCOUNT = 'ACC' # Данс
CONFIG_TYPE_PARENT_ACCOUNT = 'PAR' # Эцэг данс
CONFIG_TYPE_MENU_ACCOUNT = 'MEN' # Дансны меню
CONFIG_TYPE_DOCUMENT = 'DOC' # Текст word document 
CONFIG_TYPE_MATERIAL_TYPE = 'MIT' # Барааны төрөл
CONFIG_TYPE_USER = 'USR' # Хэрэглэгчийн төрөл
CONFIG_TYPE_JOB_POSITION = 'JOB' # Албан тушаалын төрөл
# APPLICATIONS.CONFIG MODEL - Модулийн төрөл
MODULE_TYPE_COMPANY = "COM" # Байгууллагын мэдээлэл
MODULE_TYPE_GENERAL = "GEN" # Ерөнхий модул
MODULE_TYPE_ACCOUNT = "ACC" # Дансны модул
MODULE_TYPE_CURRENCY = "CUR" # Гүйлгээний модул
MODULE_TYPE_INVENTORY = "INV" # Бараа материалын модул
MODULE_TYPE_CONTRACT = "CON" # Гэрээний модул


# APPLICATIONS.CONTRACT.CONTRACT VIEWS & FORM - formset prefix
CONTRACT_DOOR_PREFIX = 'contractorder_set' # Хаалга захиалгын prefix
CONTRACT_EXTRA_PREFIX = 'contractextraorder_set' # Дагалдах хэрэгсэл захиалгын prefix
# APPLICATIONS.CONTRACT.CONTRACT - CONTRACT MODEL - PAYMENT_TYPE_CHOICES
CONTRACT_PAYMENT_TYPE_CASH = 'C' # Бэлнээр
CONTRACT_PAYMENT_TYPE_ACCOUNT = 'A' # Дансаар
CONTRACT_PAYMENT_TYPE_BARTER = 'B' # Бартераар
# APPLICATIONS.WORKSHEET.CONTRACT - CONTRACTWORKSHEET MODEL - STATUS_CHOICES
WORKSHEET_STATUS_NOT_MEASURED = '1' # Хэмжээ аваагүй
WORKSHEET_STATUS_MEASURED = '2' # Хэмжээ авсан
WORKSHEET_STATUS_MUST_PRODUCE = '3' # Үйлдвэрт оруулах шаардлагатай
WORKSHEET_STATUS_PRODUCING = '4' # Үйлдвэрт оруулсан
WORKSHEET_STATUS_PRODUCED = '5' # Хийгдсэн
WORKSHEET_STATUS_CANCELLED = '0' # Цуцлагдсан
# APPLICATIONS.WORKSHEET.CONTRACT - CONTRACTFULLSIZE MODEL - NALICHNIK_CHOICES
WORKSHEET_NALICHNIK_SQUARE = '1' # Дөрвөлжин
WORKSHEET_NALICHNIK_ROUND = '2' # Бөөрөнхий
WORKSHEET_NALICHNIK_DECORATED = '3' # Гоёлын
WORKSHEET_NALICHNIK_OTHER = '0' # Бусад

FILTER_AVAILABLE = 'ACT'
FILTER_INAVAILABLE = 'INACT'
FILTER_DELETED = 'DEL'
FILTER_ALL = 'ALL'

WORKSHEET_MATERIAL_NOT   = '2'
WORKSHEET_MATERIAL_HALF  = '3'
WORKSHEET_MATERIAL_FULL  = '4'
WORKSHEET_MATERIAL_OTHER = '1'
